{
 "title": "Dasboard Cristian Leiton V",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "@timestamp:[2024-01-01T00:00:00Z TO 2024-03-01T23:59:59Z] AND data.usuariosConectados:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Usuarios conectados (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "data.usuariosConectados", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta (avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "responseTime", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}